### ISSUE TITLE
Not able to format source code with #:: in it

### ISSUE THREAD

**Issue by olecve** [weavejester/cljfmt#125] opened 2018-06-24 13:50 UTC
Hi!

lein-cljfmt 0.5.7 fails on following source code

```clojure
(ns ui-app.re-frame.db)

(def default-db #::{:page :home})
```

my project dependencies are

```clojure
[org.clojure/clojure "1.9.0"]
[org.clojure/clojurescript "1.10.238" :scope "provided"]
[lein-cljfmt "0.5.7"]
```

I tried to exclude rewrite-clj and use [rewrite-clj "0.6.0"], but it doesn't help

**Comment by danielcompton** [comment] 2018-06-24 23:13
@olecve can you share how it failed? What was the stacktrace?

**Comment by olecve** [comment] 2018-06-25 07:01
@danielcompton please find the log with stacktrace below

```
Reformatting src/cljs/ui_app/activities_view/core.cljs
Failed to format file: src/cljs/ui_app/re_frame/db.cljs
clojure.lang.ExceptionInfo: Invalid token: :
 at clojure.core$ex_info.invokeStatic (core.clj:4617)
    clojure.core$ex_info.invoke (core.clj:4617)
    clojure.tools.reader.reader_types$reader_error.invokeStatic (reader_types.clj:391)
    clojure.tools.reader.reader_types$reader_error.doInvoke (reader_types.clj:387)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.tools.reader.edn$read_keyword.invokeStatic (edn.clj:269)
    clojure.tools.reader.edn$read_keyword.invoke (edn.clj:257)
    clojure.tools.reader.edn$read.invokeStatic (edn.clj:369)
    clojure.tools.reader.edn$read.invoke (edn.clj:337)
    clojure.tools.reader.edn$read.invokeStatic (edn.clj:358)
    clojure.tools.reader.edn$read.invoke (edn.clj:337)
    clojure.tools.reader.edn$read.invokeStatic (edn.clj:355)
    clojure.tools.reader.edn$read.invoke (edn.clj:337)
    rewrite_clj.parser.keyword$parse_keyword.invokeStatic (keyword.clj:14)
    rewrite_clj.parser.keyword$parse_keyword.invoke (keyword.clj:8)
    rewrite_clj.parser.core$eval2753$fn__2754.invoke (core.clj:95)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    rewrite_clj.reader$read_with_meta.invokeStatic (reader.clj:132)
    rewrite_clj.reader$read_with_meta.invoke (reader.clj:128)
    rewrite_clj.parser.core$parse_next.invokeStatic (core.clj:34)
    rewrite_clj.parser.core$parse_next.invoke (core.clj:32)
    rewrite_clj.reader$read_n.invokeStatic (reader.clj:153)
    rewrite_clj.reader$read_n.invoke (reader.clj:145)
    rewrite_clj.parser.core$parse_printables.invokeStatic (core.clj:49)
    rewrite_clj.parser.core$parse_printables.doInvoke (core.clj:45)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    rewrite_clj.parser.core$eval2765$fn__2766.invoke (core.clj:140)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    rewrite_clj.reader$read_with_meta.invokeStatic (reader.clj:132)
    rewrite_clj.reader$read_with_meta.invoke (reader.clj:128)
    rewrite_clj.parser.core$parse_next.invokeStatic (core.clj:34)
    rewrite_clj.parser.core$parse_next.invoke (core.clj:32)
    rewrite_clj.parser.core$parse_delim$fn__2723.invoke (core.clj:42)
    rewrite_clj.reader$read_repeatedly$fn__1907.invoke (reader.clj:141)
    clojure.core$repeatedly$fn__5339.invoke (core.clj:4945)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$take_while$fn__4836.invoke (core.clj:2795)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:688)
    clojure.core$next__4341.invokeStatic (core.clj:64)
    clojure.core$dorun.invokeStatic (core.clj:3033)
    clojure.core$doall.invokeStatic (core.clj:3039)
    clojure.core$doall.invoke (core.clj:3039)
    rewrite_clj.reader$read_repeatedly.invokeStatic (reader.clj:143)
    rewrite_clj.reader$read_repeatedly.invoke (reader.clj:137)
    rewrite_clj.parser.core$parse_delim.invokeStatic (core.clj:43)
    rewrite_clj.parser.core$parse_delim.invoke (core.clj:38)
    rewrite_clj.parser.core$eval2789$fn__2790.invoke (core.clj:170)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    rewrite_clj.reader$read_with_meta.invokeStatic (reader.clj:132)
    rewrite_clj.reader$read_with_meta.invoke (reader.clj:128)
    rewrite_clj.parser.core$parse_next.invokeStatic (core.clj:34)
    rewrite_clj.parser.core$parse_next.invoke (core.clj:32)
    rewrite_clj.parser$parse.invokeStatic (parser.clj:13)
    rewrite_clj.parser$parse.invoke (parser.clj:10)
    rewrite_clj.parser$parse_all$fn__2806.invoke (parser.clj:18)
    clojure.core$repeatedly$fn__5339.invoke (core.clj:4945)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$take_while$fn__4836.invoke (core.clj:2795)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:688)
    clojure.core$next__4341.invokeStatic (core.clj:64)
    clojure.core$dorun.invokeStatic (core.clj:3033)
    clojure.core$doall.invokeStatic (core.clj:3039)
    clojure.core$doall.invoke (core.clj:3039)
    rewrite_clj.parser$parse_all.invokeStatic (parser.clj:20)
    rewrite_clj.parser$parse_all.invoke (parser.clj:15)
    rewrite_clj.parser$parse_string_all.invokeStatic (parser.clj:35)
    rewrite_clj.parser$parse_string_all.invoke (parser.clj:32)
    cljfmt.core$reformat_string.invokeStatic (core.cljc:314)
    cljfmt.core$reformat_string.doInvoke (core.cljc:313)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    leiningen.cljfmt$reformat_string.invokeStatic (cljfmt.clj:33)
    leiningen.cljfmt$reformat_string.invoke (cljfmt.clj:32)
    leiningen.cljfmt$fix$fn__3844.invoke (cljfmt.clj:135)
    leiningen.cljfmt$fix.invokeStatic (cljfmt.clj:134)
    leiningen.cljfmt$fix.doInvoke (cljfmt.clj:125)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.cljfmt$cljfmt.invokeStatic (cljfmt.clj:149)
    leiningen.cljfmt$cljfmt.doInvoke (cljfmt.clj:144)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__4667.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.with_profile$with_profiles_STAR_.invokeStatic (with_profile.clj:14)
    leiningen.with_profile$with_profiles_STAR_.invoke (with_profile.clj:8)
    leiningen.with_profile$apply_task_with_profiles.invokeStatic (with_profile.clj:53)
    leiningen.with_profile$apply_task_with_profiles.invoke (with_profile.clj:45)
    leiningen.with_profile$with_profile$fn__9172.invoke (with_profile.clj:85)
    clojure.core$mapv$fn__6953.invoke (core.clj:6627)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:167)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$mapv.invokeStatic (core.clj:6618)
    clojure.core$mapv.invoke (core.clj:6618)
    leiningen.with_profile$with_profile.invokeStatic (with_profile.clj:85)
    leiningen.with_profile$with_profile.doInvoke (with_profile.clj:63)
    clojure.lang.RestFn.invoke (RestFn.java:494)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__4667.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
```

**Comment by MatthewDarling** [comment] 2018-08-31 15:00
It looks like the problem is `tools.reader`, rather than `rewrite-clj`. If you run `lein deps lein deps :plugin-tree`, can you see what version of `org.clojure/tools.reader` is used?

The latest version of `tools.reader` is `1.3.0`, released in July 2018. The issue may be fixed somewhere in there, though unfortunately the changelog hasn't been kept up to date lately, making it hard to tell.

**Comment by PEZ** [comment] 2018-11-19 22:20
Is there any workaround for this problem? It is biting [Calva Formatter](/BetterThanTomorrow/calva-fmt) as well. This issue seems to be related: rundis/rewrite-cljs#14

**Comment by PEZ** [comment] 2018-11-19 23:23
In Calva Formatter it is `rewrite-cljs` that is in play, btw.

I have now tried to update the dependencies of `rewrite-cljs` to use `[org.clojure/tools.reader "1.3.2"]` and then made a version of `cljfmt` using my patched `rewrite-cljs` and I still get a very similar result to what @olecve got. Stack trace below. Not sure what to make of it. `tools.reader` shouldn't have a problem with this still, right?

Here's the trace:

```
Error: /Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs.tools.reader.impl.errors.js:52
throw cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2(full_msg,details);
^

Error: [line 3, col 20] Invalid token: :
    at new cljs$core$ExceptionInfo (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:11152:1)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:11181:1)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:11181:1)
    at Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:29:3)
    at Function.cljs.tools.reader.impl.errors.reader_error.cljs$core$IFn$_invoke$arity$variadic (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:39:1)
    at Object.rewrite_clj$reader$read_keyword [as read_keyword] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:190:7)
    at rewrite_clj$parser$keyword$parse_keyword (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/keyword.cljs:11:7)
    at Object.rewrite_clj$reader$read_with_meta [as read_with_meta] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:125:21)
    at rewrite_clj$parser$core$parse_next (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:168:1)
    at Object.rewrite_clj$reader$read_n [as read_n] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:158:7)
    at Function.rewrite_clj.parser.core.parse_printables.cljs$core$IFn$_invoke$arity$variadic (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:30:3)
    at Object.rewrite_clj$parser$core$parse_printables [as parse_printables] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:26:1)
    at rewrite_clj$parser$core$parse_sharp (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:91:3)
    at Object.rewrite_clj$reader$read_with_meta [as read_with_meta] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:125:21)
    at rewrite_clj$parser$core$parse_next (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:168:1)
    at /Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:22:9
    at /Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:145:8
    at cljs.core.repeatedly.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:4975:8)
    at cljs.core.LazySeq.sval (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3398:7)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3389:1)
    at Object.cljs$core$seq [as seq] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1210:7)
    at cljs.core.take_while.cljs$core$IFn$_invoke$arity$2 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9502:6)
    at cljs.core.LazySeq.sval (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3398:7)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3389:1)
    at Object.cljs$core$seq [as seq] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1210:7)
    at cljs.core.Cons.cljs$core$INext$_next$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3232:25)
    at Object.cljs$core$next [as next] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1255:7)
    at Function.cljs.core.dorun.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9795:4)
    at Function.cljs.core.doall.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9801:1)
    at Object.rewrite_clj$reader$read_repeatedly [as read_repeatedly] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:141:1)
    at Object.rewrite_clj$parser$core$parse_delim [as parse_delim] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:24:8)
    at rewrite_clj$parser$core$parse_list (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:51:1)
    at Object.rewrite_clj$reader$read_with_meta [as read_with_meta] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/reader.cljs:125:21)
    at Object.rewrite_clj$parser$core$parse_next [as parse_next] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser/core.cljs:168:1)
    at Object.rewrite_clj$parser$parse [as parse] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser.cljs:8:1)
    at /Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser.cljs:16:20
    at cljs.core.repeatedly.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:4975:8)
    at cljs.core.LazySeq.sval (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3398:7)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3389:1)
    at Object.cljs$core$seq [as seq] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1210:7)
    at cljs.core.take_while.cljs$core$IFn$_invoke$arity$2 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9502:6)
    at cljs.core.LazySeq.sval (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3398:7)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3389:1)
    at Object.cljs$core$seq [as seq] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1210:7)
    at cljs.core.Cons.cljs$core$INext$_next$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:3232:25)
    at Object.cljs$core$next [as next] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:1255:7)
    at Function.cljs.core.dorun.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9795:4)
    at Function.cljs.core.doall.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljs/core.cljs:9801:1)
    at Object.rewrite_clj$parser$parse_all [as parse_all] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser.cljs:13:1)
    at Object.rewrite_clj$parser$parse_string_all [as parse_string_all] (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/rewrite_clj/parser.cljs:30:1)
    at Function.cljfmt.core.reformat_string.cljs$core$IFn$_invoke$arity$2 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljfmt/core.cljc:382:1)
    at Function.cljfmt.core.reformat_string.cljs$core$IFn$_invoke$arity$1 (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljfmt/core.cljc:382:1)
    at cljfmt$core$reformat_string (/Users/pez/Projects/calva-fmt/.shadow-cljs/builds/calva-fmt-lib/dev/out/cljs-runtime/cljfmt/core.cljc:382:1)
```

**Comment by PEZ** [comment] 2018-11-21 12:21
@replomancer: Now that you are getting warmed up on this codebase. :smile: Maybe you can help investigate this mystery? It will probably bring you over to `rewrite-cli(s)` as well, and possibly beyond, but anyway, we need more clues!

I am surprised we don't hear about this issue from more people. Is this syntax that rare out there?

**Comment by replomancer** [comment] 2018-11-21 15:10
I can't promise anything, but I'll take a look later.

**Comment by lread** [comment] 2018-12-10 15:57
Looks like clj-rewrite has [yet to add support for self-namespaced maps](https://github.com/xsc/rewrite-clj/pull/66).

I'll add tests for  keyword-namespaced maps and alias-namespaced maps which seem to work fine.

**Comment by lread** [comment] 2018-12-14 21:17
After that I'll swing over to [rewrite-cljs and have a peek](https://github.com/rundis/rewrite-cljs/issues/14).

**Comment by lread** [comment] 2018-12-17 18:18
I've [got a pull request up at rewrite-clj](https://github.com/xsc/rewrite-clj/pull/71).  After it is deemed good and sound, I'll take a stab at adding same support to rewrite-cljs.

**Closed** 2020-08-09 11:32 UTC
