### ISSUE TITLE
Warnings when I compile `master`

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#224] opened 2021-04-18 13:23 UTC
Hello,

When I run `lein install` I get these warnings:

```
% lein install
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Warning: implicit hook found: leiningen.cljsbuild/activate 
Hooks are deprecated and will be removed in a future version.
Compiling ClojureScript...
Compiling ["target/out/tests.js"] from ["src" "test"]...
WARNING: rewrite-clj.zip.whitespace/prepend-space is deprecated at line 106 target/out/rewrite_clj/zip/whitespace.cljc
WARNING: rewrite-clj.zip.whitespace/append-space is deprecated at line 113 target/out/rewrite_clj/zip/whitespace.cljc
WARNING: rewrite-clj.zip.whitespace/prepend-newline is deprecated at line 120 target/out/rewrite_clj/zip/whitespace.cljc
WARNING: rewrite-clj.zip.whitespace/append-newline is deprecated at line 127 target/out/rewrite_clj/zip/whitespace.cljc
WARNING: rewrite-clj.node.protocols/value is deprecated at line 88 target/out/rewrite_clj/zip/base.cljc
WARNING: rewrite-clj.node.protocols/value is deprecated at line 207 target/out/rewrite_clj/node.cljc
WARNING: rewrite-clj.zip.base/value is deprecated at line 253 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.base/->string is deprecated at line 273 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.base/->root-string is deprecated at line 283 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/prepend-space is deprecated at line 886 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/prepend-space is deprecated at line 887 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/append-space is deprecated at line 892 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/append-space is deprecated at line 893 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/prepend-newline is deprecated at line 898 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/prepend-newline is deprecated at line 899 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/append-newline is deprecated at line 904 target/out/rewrite_clj/zip.cljc
WARNING: rewrite-clj.zip.whitespace/append-newline is deprecated at line 905 target/out/rewrite_clj/zip.cljc
Successfully compiled ["target/out/tests.js"] in 6.12 seconds.
Created /Users/pez/Projects/cljfmt/cljfmt/target/cljfmt-0.7.0-pez-testing.jar
Wrote /Users/pez/Projects/cljfmt/cljfmt/pom.xml
Installed jar and pom into local repo.
```

I also get errors trying to use this in my shadow-cljs build, but I'll file a separate issue about that, b/c yeah separate issue maybe. 😄 

Ping @lread .

**Comment by weavejester** [comment] 2021-04-18 14:13
These warnings aren't caused by the cljfmt codebase, but in rewrite-clj, so I'll close this.

**Closed by weavejester** 2021-04-18 14:13 UTC

**Comment by lread** [comment] 2021-04-28 17:38
@PEZ, feel free to re-raise this one as-is over at [rewrite-clj](https://github.com/clj-commons/rewrite-clj) if you like.

I can see that the deprecation warnings would be annoying/confusing/misleading.

FWIW, I typically turn deprecation warnings off for cljs builds and instead rely on clj-kondo, which offers finer control over which deprecation warnings are raised.
