### ISSUE TITLE
Incorrect formatting when multiple blank lines at end of file

### ISSUE THREAD

**Issue by noisesmith** [weavejester/cljfmt#144] opened 2018-11-09 00:49 UTC
project.clj:

```
(defproject bad-reformat-diff "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-cljfmt "0.6.1"]]
  :dependencies [[org.clojure/clojure "1.9.0"]])
```

source file:

```
(ns bad-reformat-diff.core
  (:require [clojure.test :refer :all]))

(defn -main
  [& args]
  (println args))





```

output:

```
src/bad_reformat_diff/core.clj has incorrect formatting
--- a/Users/justin.smith/bad-reformat-diff/src/bad_reformat_diff/core.clj
+++ b/Users/justin.smith/bad-reformat-diff/src/bad_reformat_diff/core.clj
@@ -3,4 +3,6 @@
 
 (defn -main
   [& args]
-  (println args))
+  (println
+
+   args))
1 file(s) formatted incorrectly
```

instead of showing a diff for the trailing empty lines, it imposes a line break in the middle of the function call

**Comment by noisesmith** [comment] 2018-11-09 00:51
using fix instead of check just makes the change the diff would suggest (leaving the trailing whitespace, and imposing an empty line in the middle of the function call)

**Comment by weavejester** [comment] 2018-11-09 01:00
I can't reproduce your results. I get:

```
$ lein cljfmt check
All source files formatted correctly
```

Do you have any plugins installed to your `~/.lein/profiles.clj` that might be affecting things?

**Comment by weavejester** [comment] 2018-11-09 01:03
Ah, wait, I see the newlines in your example now. I can reproduce your issue when I add in those blank lines.

**Comment by lread** [comment] 2018-12-09 22:44
I can look at this one.  

Given that I fix up the mis-formatting, I suppose `:remove-consecutive-blank-lines?` should transform multiple blank lines at the end of a file to a single newline.

For consistency, we might also consider what to do with blank lines at the top of a file, but I'll leave that out of scope for this issue.

**Comment by simon-katz** [comment] 2018-12-09 22:56
Perhaps, as you say, `:remove-consecutive-blank-lines?` should imply removing trailing blank lines, but it would be good if there were a way to remove trailing blank lines and leave other blank lines unchanged.

**Comment by lread** [comment] 2018-12-09 23:01
Hmmm, I like that.  It allows me to fix the formatting only for this issue.  Someone, if it is important to them, can raise a separate issue on how to deal with blank lines at the end of (and maybe beginning of) a file.

**Closed** 2018-12-10 11:33 UTC
