### ISSUE TITLE
Some trailing whitespace remains after `lein cljfmt fix`

### ISSUE THREAD

**Issue by xpe** [weavejester/cljfmt#34] opened 2015-03-13 17:04 UTC
For example, I'm working through `lein cljfmt fix` as of this commit of liberator: https://github.com/clojure-liberator/liberator/commit/9b210244d78c6a4fd35d83823016f517c0d52e37

Here is some example output:

![example-liberator](https://cloud.githubusercontent.com/assets/4576329/6643288/8b3b7326-c981-11e4-901c-c37b305cf731.png)

**Comment by weavejester** [comment] 2015-07-02 16:56
This may be fixed in 0.1.11, or at least, I can't reproduce it. Can you confirm @xpe?

**Comment by weavejester** [comment] 2015-07-28 03:00
Closing for now.

**Closed by weavejester** 2015-07-28 03:00 UTC
