### ISSUE TITLE
Formatting of closing parens etc on a new line

### ISSUE THREAD

**Issue by simon-katz** [weavejester/cljfmt#127] opened 2018-07-22 10:48 UTC
I'm using clj-fmt 0.6.0.

The formatting I'm getting for closing parens etc on a new line seems wrong to me (by what I'm used to from CIDER, Emacs Lisp and Common Lisp).

For example the following (which I think is indented correctly)…

```clojure
(def v
  [[first-thing
    second-thing ; a comment that applies just to `second-thing`
    ]
   [:a
    ;; :b ; -- commented this out temporarily
    ]
   (foo 1
        2
        3 ; -- commented this out temporarily
        )])
```

…gets changed to…

```clojure
(def v
  [[first-thing
    second-thing ; a comment that applies just to `second-thing`
]
   [:a
    ;; :b ; -- commented this out temporarily
]
   (foo 1
        2
        3 ; -- commented this out temporarily
)])
```

**Comment by weavejester** [comment] 2018-07-22 13:18
This looks like a duplicate of #82.

**Closed by weavejester** 2018-07-22 13:18 UTC
