### ISSUE TITLE
Thread macro is not honored

### ISSUE THREAD

**Issue by introom** [weavejester/cljfmt#248] opened 2022-03-08 14:26 UTC
Give the following code:
```
(-> zz
    (as-> x
          foo))
```

It should be formatted as:
```
(-> zz
    (as-> x
        foo))
```
Which also happens to be what emacs clojure mode does.

However, cljfmt thinks the code is already formatted.

Steps to reproduce:
 clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.8.0"}}}'  -m cljfmt.main check example.clj

**Comment by weavejester** [comment] 2022-03-08 15:02
Why should it be formatted that way? Can you give some justification?

**Comment by introom** [comment] 2022-03-08 15:11
It's like macro body forms two spaces indented.

foo here belongs to the body part.

https://github.com/bbatsov/clojure-style-guide#body-indentation

**Comment by introom** [comment] 2022-03-08 15:12
Similar to the fashion foo is indented here:
```
(as-> y x
  foo)
```

**Comment by introom** [comment] 2022-03-08 15:40
The issue is not about the format of -> but rather the inconsistency on how cljfmt handles as->.

Cljfmt requires that the body form to be two space indents, for example,
```
;; cljfmt thinks foo is correctly indented (1)
(as-> y
      x
  foo)

;; cljfmt thinks foo is not correctly indented (2)
(as-> y
      x
      foo)
```

The problem is, when the as-> is inside thread->, an implicit argument is placed; however, cljfmt seems to ignore it and formats it similar to the above case (2).
```
(-> y
    (as-> x
          foo))
```

**Comment by weavejester** [comment] 2022-03-08 15:55
Ah, yes, that's a known missing feature. Currently cljfmt is not aware of the threading macros when handling block indentation.

**Comment by or** [comment] 2022-05-10 08:24
Duplicate of https://github.com/weavejester/cljfmt/issues/223.

**Comment by weavejester** [comment] 2023-02-02 15:14
Closed due to duplicate.

**Closed by weavejester** 2023-02-02 15:14 UTC
