### ISSUE TITLE
Default formatting not aligning let blocks statements vertically

### ISSUE THREAD

**Issue by cksharma11** [weavejester/cljfmt#201] opened 2020-08-09 09:46 UTC
I want to format my code something like below

from this
```
(let [username "username"
      pwd "pwd"
      email "email"])
```
to this
```
(let [username "username"
      pwd      "pwd"
      email    "email"])
```

But when I'm doing `lein cljfmt check` it's not giving any error for the same.

**Comment by weavejester** [comment] 2020-08-09 11:31
cljfmt does not yet support this feature. PRs are welcome.

**Comment by weavejester** [comment] 2020-08-09 11:33
Closing because this is a duplicate of #36.

**Closed by weavejester** 2020-08-09 11:33 UTC
