### ISSUE TITLE
Does not flag extra linespaces

### ISSUE THREAD

**Issue by xpe** [weavejester/cljfmt#37] opened 2015-03-30 20:29 UTC
Currently cljfmt doesn't flag extra newlines; e.g.

```clj
(def a 1)


(def b 2)
```

**Comment by xpe** [comment] 2015-04-06 14:15
I'm digging into this a little bit. I'm not sure yet if the easiest/best fix belongs in `cljfmt/core` or https://github.com/xsc/rewrite-clj. If anyone has ideas, I'm all ears.

**Comment by weavejester** [comment] 2015-04-06 14:47
This is a feature that needs to be added to cljfmt. It's not a bug fix. This functionality does not exist in cljfmt yet.

**Comment by xpe** [comment] 2015-04-06 19:50
@weavejester How does this look? https://github.com/orphid/cljfmt/commit/f50d864bc24f8b0ab24898234ba1254e4b9a6f04

**Comment by weavejester** [comment] 2015-04-06 23:07
@xpe, try to follow the same design as the rest of the source code. Don't operate directly on the string; instead, operate on the parsed form generated by rewrite-clj.

If you operate directly on the raw source text, your code has no idea of the context. Your code will remove consecutive newlines in literal strings, which clearly isn't what we want.

There's also no need to docstring private functions whose purpose is obvious, and private functions should be marked as such with metadata (or via `defn-`).

**Comment by xpe** [comment] 2015-04-07 14:50
My goal was to change `(\n){3,}` to `\n\n`, nothing more, nothing less, across the entire file -- in forms, outside of forms, between forms. (I was seeing extra newlines sneak into Clojure files unnecessarily.) See what I mean? If you see a better way to achieve a similar or better goal, I'm all ears.

If you are open to a goal along these lines, I'll work a PR to your desired style. (Still, I don't see how a docstring hurts (quite the opposite), but if you insist on no docstring, that's your prerogative.)

As for the fork I maintain, these things work well for us:

* We find docstrings to be valuable; they don't hurt, can drive out bugs, and improve clarity.
* Marking functions as private makes them hard to test. I like to use `^:internal` metadata to denote an internal function (e.g. not intended for outside use).
* Perhaps because of missing docstrings, perhaps because of uncommunicative argument names, some of the private functions in cljfmt and lein-cljfmt were not obvious -- even confusing: https://github.com/orphid/cljfmt/commit/815f65e87708acc3ae907dc1052ac04d71f6c4e1 This mixup made it hard for me to dig into the code. There is a big difference between a `form` an `forms-node`.

**Comment by weavejester** [comment] 2015-04-07 15:27
cljfmt is a tool for changing the formatting of a file; it should not change how the code functions. Simply removing consecutive newlines without taking the context into consideration could potentially break a person's code. For instance, if you had code like:

```clojure
(def help-message
  "foo


  bar")
```

Then your code would replace the consecutive newlines within the string. Obviously this is something we want to avoid.

Instead, we want to work within the parse-tree generated by rewrite-clj, as that allows us to be certain that we're changing the formatting of the code, and not the meaning of the code.

This means writing something more like:

```clojure
(defn remove-consecutive-newlines [form]
  (transform form edit-all consecutive-newline? zip/remove))
```

The idea of a post-processing step is unnecessary, because rewrite-clj exposes every part of the underlying text, including whitespace, newlines and comments. The only time we'd need some manner of post-processing is if we were consuming, or producing, text that wasn't valid Clojure. I don't foresee that being necessary in a Clojure formatting tool.

Regarding `form` vs. `forms-node`, I don't believe the distinction is necessary, because in the cljfmt source, "form" means "a rewrite-clj form".

Regarding private functions and testing, I believe that tests should test the functionality of the library, not it's internal mechanisms. A formatting tool is relatively straightforward to test, because it takes a string as an input, and returns a string as output.

Docstrings on private functions are, I think, mostly unnecessary, because private functions aren't exposed as an API. The purpose of a function should ideally be clear from its name or structure, and docstrings add additional verbosity that means less can be seen at a glance.

**Comment by xpe** [comment] 2015-04-07 16:04
> cljfmt is a tool for changing the formatting of a file; it should not change how the code functions.

I see now (but didn't before) that changing "\n\n\n" to "\n\n" **in** a string could break code. Good point. My mistake. I'll take a swing at using rewrite-clj as you suggest.

> Regarding form vs. forms-node, I don't believe the distinction is necessary, because in the cljfmt source, "form" always means "a rewrite-clj form".

Now that I've been exposed / indoctrinated into the code, I can see why you say this. However, this is only apparent once a person has thought through and perhaps tried out the code. I'd suggest something like a comment or perhaps docstring at the top of the file to make this clear to newcomers; e.g.

```clj
(ns cljfmt.core
  "Internal conventions for arguments:
   * form-string indicates a string
   * form indicates a FormsNode from rewrite-clj")
```

> Regarding private functions and testing, I believe that tests should test the functionality of the library, not it's internal mechanisms.

This is a valid and common argument in isolation; however, it is the whole story, in my experience. In any case, I'm not going to try to sway you here.

> The idea of a post-processing step is unnecessary, because rewrite-clj exposes every part of the underlying text, including whitespace, newlines and comments. The only time we'd need some manner of post-processing is if we were consuming, or producing, text that wasn't valid Clojure. I don't foresee that being necessary in a Clojure formatting tool.

Fair point.

**Comment by weavejester** [comment] 2015-04-07 16:23
I might add a comment to further explain the conventions in the code. cljfmt also relies a lot on a good understanding of rewrite-clj and zippers, which perhaps makes it harder to understand.

You probably want something like:

```clojure
(defn- consecutive-newline? [zloc]
  (and (z/linebreak? zloc) (-> zloc z/right skip-whitespace z/linebreak?)))

(defn remove-consecutive-newlines [form]
  (transform form edit-all consecutive-newline? zip/remove))
```

Although you might need to remove the indentation as well, so perhaps `(-> zloc skip-whitespace z/linebreak?)`.

**Comment by xpe** [comment] 2015-04-07 16:34
Thanks for the example. It looks like it checks for two consecutive newlines. Right? My hope was to only flag on three.

**Comment by weavejester** [comment] 2015-04-07 16:46
Right, yes. I was thinking in terms of blank lines, rather than newlines. You'd just need to add an additional part to the `and` form to make it three.

**Closed** 2015-07-03 15:43 UTC
