### ISSUE TITLE
Formatting of `letfn`

### ISSUE THREAD

**Issue by simon-katz** [weavejester/cljfmt#126] opened 2018-07-22 10:21 UTC
I'm using clj-fmt 0.6.0.

The formatting I'm getting for `letfn` isn't right.

I would hope to get this:

```clojure
(letfn [(double [x]
          (* x 2)) ; special indentation here
        (triple [x]
          (* x 3)) ; special indentation here
        (quadruple [x]
          (* x 4))] ; special indentation here
  (println "Trying more than one form in the `letfn` body.")
  (println "Trying more than one form in the `letfn` body.")
  (let [y (double 2)
        z (double 3)]
    (println y
             z))) ; but not here
```

Without adding my own `letfn` rule, the first function that is being defined indents correctly but subsequent functions don't:

```clojure
(letfn [(double [x]
          (* x 2)) ; special indentation here
        (triple [x]
                (* x 3)) ; special indentation here
        (quadruple [x]
                   (* x 4))] ; special indentation here
  (println "Trying more than one form in the `letfn` body.")
  (println "Trying more than one form in the `letfn` body.")
  (let [y (double 2)
        z (double 3)]
    (println y
             z))) ; but not here
```

If I add the `{letfn [[:inner 2 0]]}` rule suggested in the README, in addition to the above the body of the `letfn` is indented wrongly:

```clojure
(letfn [(double [x]
          (* x 2)) ; special indentation here
        (triple [x]
                (* x 3)) ; special indentation here
        (quadruple [x]
                   (* x 4))] ; special indentation here
       (println "Trying more than one form in the `letfn` body.")
       (println "Trying more than one form in the `letfn` body.")
       (let [y (double 2)
             z (double 3)]
         (println y
                  z))) ; but not here
```

FWIW, with clj-fmt 0.5.7 the behaviour was similar — it was the same as above except that adding the  `{letfn [[:inner 2 0]]}` rule made no difference.

**Comment by weavejester** [comment] 2018-07-22 13:17
This looks like a duplicate of #73.

**Closed by weavejester** 2018-07-22 13:17 UTC
