### ISSUE TITLE
lein cljfmt commands fails with 0.9.1 version

### ISSUE THREAD

**Issue by t-my** [weavejester/cljfmt#290] opened 2023-01-19 09:58 UTC
Looking to update lein plugin 0.8 -> 0.9.1 but after the update:
```
$ lein cljfmt check
clojure.lang.ArityException: Wrong number of args (1) passed to: cljfmt.main/merge-default-options
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:32)
    leiningen.cljfmt$cljfmt.invokeStatic (cljfmt.clj:30)
    leiningen.cljfmt$cljfmt.doInvoke (cljfmt.clj:21)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:669)
    clojure.core$apply.invoke (core.clj:662)
    leiningen.core.main$partial_task$fn__7340.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:669)
    clojure.core$apply.invoke (core.clj:662)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__7429.invoke (main.clj:453)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.main$main_opt.invokeStatic (main.clj:514)
    clojure.main$main_opt.invoke (main.clj:510)
    clojure.main$main.invokeStatic (main.clj:664)
    clojure.main$main.doInvoke (main.clj:616)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:40)
```
I can see some CLI related changes in https://github.com/weavejester/cljfmt/commit/cf708becf6e202ef0bc8c635aebbc49be7cd1c61 🤔

**Comment by weavejester** [comment] 2023-01-20 00:17
Duplicate of issue #289. This was fixed by 0.9.2 - sorry for the trouble.

**Closed by weavejester** 2023-01-20 00:17 UTC
