### ISSUE TITLE
Parens after trailing comment not indented

### ISSUE THREAD

**Issue by arrdem** [weavejester/cljfmt#111] opened 2018-01-22 23:25 UTC
I encountered this bug while trying to format a codebase. It looks like the trailing comment causes the computation of the last indentation width not to occur correctly. If there's a trailing newline, it seems that the computed indentation width is `0` somehow, otherwise the left margin of the previous form seems to win.

Neither of these is expected behavior, I'd expect that the closing stack of parenthesis always be indented to the body width of the let being closed.

## Ex 1. Close paren stacks after comments not correctly indented

```clojure
cljfmt.core> (print (reformat-string "(deftest foo
  (testing \"testing foo\"
    (let []
      ;; this messes up
      )))"))
(deftest foo
  (testing "testing foo"
    (let []
      ;; this messes up
         )))
nil
```

## Ex 2. Newline after paren stack impacts behavior

```
cljfmt.core> (print (reformat-string "(deftest foo
  (testing \"testing foo\"
    (let []
      ;; this messes up
      )))
"))
(deftest foo
  (testing "testing foo"
    (let []
      ;; this messes up
)))
nil
cljfmt.core> 
```

**Comment by MatthewDarling** [comment] 2018-01-23 15:49
Seems related to #82. Which you had said in ~16 months ago "shouldn't be too hard to fix", haha.

At least, Ex 2 seems the same as that issue. Ex 1 is new to me, but it seems likely to be the same underlying problem.

When I was working on it, it was proving difficult because parens don't actually have nodes in the tree. Although, thinking about it now - I wonder if end-of-line comments could have indentation logic which inserts whitespace to the tree after themselves? Depending on how `#_` and `(comment ... )` are parsed, might have to treat them differently from semi-colon comments.

**Comment by arrdem** [comment] 2018-01-23 18:01
Argh 😄 well, I guess it's time for me to eat my words. I'll see if I can pick this up today.

**Comment by dijonkitchen** [comment] 2018-08-28 19:06
Should this be closed since it's a duplicate of #82?

**Comment by lread** [comment] 2018-11-22 20:38
This is a slight variation on #82 in that the comment line is the only line in the indent block.

**Comment by lread** [comment] 2018-12-08 23:11
At the time of this writing example 1 still behaves as reported but example 2 now behaves the same as example 1.  This currently seems to be an issue with indent blocks with no code in them.

**Closed** 2018-12-10 11:34 UTC
