### ISSUE TITLE
Align for let forms

### ISSUE THREAD

**Issue by fommil** [weavejester/cljfmt#68] opened 2016-03-20 15:20 UTC
it would be really great if `let` forms could be automatically aligned by value, e.g.

```clojure
(let [foo bar
        a baz])
```

instead of (note `baz` does not align with `bar`)

```clojure
(let [foo bar
      a baz])
```

I'd also be happy with

```clojure
(let [foo bar
      a   baz])
```

(i.e. left align the variable)

**Comment by arrdem** [comment] 2016-03-20 15:32
I've never seen right variable alignment in a let form. The double left alignment is a duplicate of https://github.com/weavejester/cljfmt/issues/36.

**Closed** 2016-03-20 17:04 UTC
