### ISSUE TITLE
Multi-line regex bodies removed

### ISSUE THREAD

**Issue by royaldark** [weavejester/cljfmt#76] opened 2016-07-06 22:17 UTC
A multi-line regex with embedded comments loses its body when cljfmt runs. See the following contrived example:

```clojure
(def pattern
  #"(?x)
    ^   # Beginning of line
    .*  # Any number of characters
    $   # End of line")
```
`lein cljfmt fix` outputs:

```clojure
(def pattern
  #"(?x)")
```

Lein 2.6.1
cljfmt 0.5.3

**Comment by weavejester** [comment] 2016-07-06 23:23
Thanks for the report. This is caused by a bug in rewrite-clj, and I've opened an issue for it.

**Comment by trimtab613** [comment] 2016-07-29 14:58
The bug in rewrite-clj has been fixed: https://github.com/xsc/rewrite-clj/issues/50

**Comment by weavejester** [comment] 2016-09-16 13:51
This is now fixed in cljfmt for Clojure (via #80), but not ClojureScript.

**Comment by trimtab613** [comment] 2016-09-16 14:00
Awesome thank you. Looking forward to 0.5.4 being published on clojars!

**Closed** 2016-09-29 13:38 UTC
Labels: bug
